### ISSUE TITLE
KeyError: ('line_keysets', 0, 0) when try train.py

### ISSUE THREAD

**Issue by 00Haocheng** [HalleyJiang/PLNet#1]
Thank you very much for sharing this excellent work, but when I run the train file, I display the error 
File "/data/whc/data_whc/PLNet main/trainer. py", line 431, in compute_ losses
line_ loss = get_ line_ loss(inputs[("line_keysets", 0, scale)], norm_ point3D)
KeyError: ('line_keysets', 0, 0)

How can I solve this problem

**Comment by hualie** [comment]
The dataloader did not load the data correctly. Please debug into the function   https://github.com/HalleyJiang/PLNet/blob/a02bd5f343b9e4766891fd234e3a338c1eaa26ff/datasets/mono_dataset.py#L178

I guess you have not pre-processed the dataset to generate lines with 'python extract_lineseg.py --data_path $DATA_PATH
'.

**Comment by 00Haocheng** [comment]
Thank you very much! I have solved this question by this way
