### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by water221** [HalleyJiang/PLNet#2]
The createLineSegmentDetector function has been removed in the preprocess/ext_lineseg.py file. Do you have an alternative or can you put the processed data set on Google Cloud Drive?

**Comment by hualie** [comment]
I did not maintain the processed data. You may install a lower version of opencv or use cv2.ximgproc.createFastLineDetector() instead.

**Comment by water221** [comment]
Thank you very much for your reply, I will try according to your tips, hope there will be a good result
