### ISSUE TITLE
About mono_dataset.py

### ISSUE THREAD

**Issue by water221** [HalleyJiang/PLNet#3]
`  File "/home/usst/zts/IndoorDepth/datasets/mono_dataset.py", line 271, in __getitem__
    self.preprocess(inputs, color_aug)
  File "/home/usst/zts/IndoorDepth/datasets/mono_dataset.py", line 135, in preprocess
    inputs[(n + "_aug", im, i)] = self.to_tensor(color_aug(f))
TypeError: 'tuple' object is not callable`
Hello, I run the train.py file after preprocessing the dataset, but the above error occurs, saying that color_aug is a tuple in the mono_dataset.py file, not a function, and cannot be called. Do you know what to do?

**Comment by hualie** [comment]
you could debug on the line https://github.com/HalleyJiang/PLNet/blob/a02bd5f343b9e4766891fd234e3a338c1eaa26ff/datasets/mono_dataset.py#L248
to see why color_aug is not initialized as a function.

**Comment by water221** [comment]
thank you，I will have a try
